# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/SoC/SoC.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC || ORIG_REF_NAME==SoC} -quiet] -quiet

# IP: bd/SoC/ip/SoC_zynq_ultra_ps_e_0_0/SoC_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==SoC_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/SoC/ip/SoC_axi_wrapper_0_0/SoC_axi_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_axi_wrapper_0_0 || ORIG_REF_NAME==SoC_axi_wrapper_0_0} -quiet] -quiet

# IP: bd/SoC/ip/SoC_xbar_0/SoC_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_xbar_0 || ORIG_REF_NAME==SoC_xbar_0} -quiet] -quiet

# IP: bd/SoC/ip/SoC_ps8_0_axi_periph_0/SoC_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_ps8_0_axi_periph_0 || ORIG_REF_NAME==SoC_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/SoC/ip/SoC_rst_ps8_0_99M_0/SoC_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_rst_ps8_0_99M_0 || ORIG_REF_NAME==SoC_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/SoC/ip/SoC_system_ila_0_0/SoC_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_system_ila_0_0 || ORIG_REF_NAME==SoC_system_ila_0_0} -quiet] -quiet

# Block Designs: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/bd_5c78.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5c78 || ORIG_REF_NAME==bd_5c78} -quiet] -quiet

# IP: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_0/bd_5c78_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5c78_ila_lib_0 || ORIG_REF_NAME==bd_5c78_ila_lib_0} -quiet] -quiet

# IP: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_1/bd_5c78_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5c78_g_inst_0 || ORIG_REF_NAME==bd_5c78_g_inst_0} -quiet] -quiet

# IP: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_2/bd_5c78_slot_0_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5c78_slot_0_aw_0 || ORIG_REF_NAME==bd_5c78_slot_0_aw_0} -quiet] -quiet

# IP: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_3/bd_5c78_slot_0_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5c78_slot_0_w_0 || ORIG_REF_NAME==bd_5c78_slot_0_w_0} -quiet] -quiet

# IP: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_4/bd_5c78_slot_0_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5c78_slot_0_b_0 || ORIG_REF_NAME==bd_5c78_slot_0_b_0} -quiet] -quiet

# IP: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_5/bd_5c78_slot_0_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5c78_slot_0_ar_0 || ORIG_REF_NAME==bd_5c78_slot_0_ar_0} -quiet] -quiet

# IP: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_6/bd_5c78_slot_0_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_5c78_slot_0_r_0 || ORIG_REF_NAME==bd_5c78_slot_0_r_0} -quiet] -quiet

# IP: bd/SoC/ip/SoC_auto_ds_0/SoC_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_auto_ds_0 || ORIG_REF_NAME==SoC_auto_ds_0} -quiet] -quiet

# IP: bd/SoC/ip/SoC_auto_pc_0/SoC_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_auto_pc_0 || ORIG_REF_NAME==SoC_auto_pc_0} -quiet] -quiet

# IP: bd/SoC/ip/SoC_auto_ds_1/SoC_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_auto_ds_1 || ORIG_REF_NAME==SoC_auto_ds_1} -quiet] -quiet

# IP: bd/SoC/ip/SoC_auto_pc_1/SoC_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==SoC_auto_pc_1 || ORIG_REF_NAME==SoC_auto_pc_1} -quiet] -quiet

# XDC: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_zynq_ultra_ps_e_0_0/SoC_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_zynq_ultra_ps_e_0_0/SoC_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SoC_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==SoC_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_xbar_0/SoC_xbar_0_ooc.xdc

# XDC: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_rst_ps8_0_99M_0/SoC_rst_ps8_0_99M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SoC_rst_ps8_0_99M_0 || ORIG_REF_NAME==SoC_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_rst_ps8_0_99M_0/SoC_rst_ps8_0_99M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SoC_rst_ps8_0_99M_0 || ORIG_REF_NAME==SoC_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5c78_ila_lib_0 || ORIG_REF_NAME==bd_5c78_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5c78_ila_lib_0 || ORIG_REF_NAME==bd_5c78_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_0/bd_5c78_ila_lib_0_ooc.xdc

# XDC: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/bd_5c78_ooc.xdc

# XDC: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/SoC_system_ila_0_0_ooc.xdc

# XDC: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_auto_ds_0/SoC_auto_ds_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SoC_auto_ds_0 || ORIG_REF_NAME==SoC_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_auto_ds_0/SoC_auto_ds_0_ooc.xdc

# XDC: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_auto_pc_0/SoC_auto_pc_0_ooc.xdc

# XDC: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_auto_ds_1/SoC_auto_ds_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==SoC_auto_ds_1 || ORIG_REF_NAME==SoC_auto_ds_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_auto_ds_1/SoC_auto_ds_1_ooc.xdc

# XDC: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/ip/SoC_auto_pc_1/SoC_auto_pc_1_ooc.xdc

# XDC: d:/University/251/DA/wrapper/wrapper.gen/sources_1/bd/SoC/SoC_ooc.xdc
