# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/University/251/DA/wrapper/wrapper.runs/synth_1/HQC_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xck26-sfvc784-2LV-c

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/University/251/DA/wrapper/wrapper.cache/wt [current_project]
set_property parent.project_path D:/University/251/DA/wrapper/wrapper.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kv260_som:part0:1.4 [current_project]
set_property ip_output_repo d:/University/251/DA/wrapper/wrapper.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  C:/Users/THUAN/Downloads/wrapper/barrett_hqc_128.mem
  C:/Users/THUAN/Downloads/wrapper/barrett_hqc_192.mem
  C:/Users/THUAN/Downloads/wrapper/barrett_hqc_256.mem
}
read_verilog -library xil_defaultlib {
  C:/Users/THUAN/Downloads/wrapper/add_fft.v
  C:/Users/THUAN/Downloads/wrapper/clog2.v
  C:/Users/THUAN/Downloads/wrapper/barrett_red_gen.v
  C:/Users/THUAN/Downloads/wrapper/cdw_xor_tmp.v
  C:/Users/THUAN/Downloads/wrapper/concat_code.v
  C:/Users/THUAN/Downloads/wrapper/keccak_pkg.v
  C:/Users/THUAN/Downloads/wrapper/control_path.v
  C:/Users/THUAN/Downloads/wrapper/keccak_math.v
  C:/Users/THUAN/Downloads/wrapper/data_path.v
  C:/Users/THUAN/Downloads/wrapper/decap.v
  C:/Users/THUAN/Downloads/wrapper/decrypt.v
  C:/Users/THUAN/Downloads/wrapper/encap.v
  C:/Users/THUAN/Downloads/wrapper/encrypt.v
  C:/Users/THUAN/Downloads/wrapper/encrypt_parallel.v
  C:/Users/THUAN/Downloads/wrapper/fft_leaves_butterfly.v
  C:/Users/THUAN/Downloads/wrapper/fft_part1.v
  C:/Users/THUAN/Downloads/wrapper/fft_part2.v
  C:/Users/THUAN/Downloads/wrapper/fft_retrieve_error_poly.v
  C:/Users/THUAN/Downloads/wrapper/fixed_weight.v
  C:/Users/THUAN/Downloads/wrapper/fixed_weight_ct.v
  C:/Users/THUAN/Downloads/wrapper/fixed_weight_cww.v
  C:/Users/THUAN/Downloads/wrapper/gf_mul.v
  C:/Users/THUAN/Downloads/wrapper/gfmul.v
  C:/Users/THUAN/Downloads/wrapper/hqc_barrett_red.v
  C:/Users/THUAN/Downloads/wrapper/hqc_decod_top.v
  C:/Users/THUAN/Downloads/wrapper/hqc_kem_joint_design.v
  C:/Users/THUAN/Downloads/wrapper/hqc_rmdecod_ctrl.v
  C:/Users/THUAN/Downloads/wrapper/hqc_rmdecod_expnsum.v
  C:/Users/THUAN/Downloads/wrapper/hqc_rmdecod_findpeaks.v
  C:/Users/THUAN/Downloads/wrapper/hqc_rmdecod_hadamard.v
  C:/Users/THUAN/Downloads/wrapper/hqc_rmdecod_top.v
  C:/Users/THUAN/Downloads/wrapper/hqc_rsdecod_elp.v
  C:/Users/THUAN/Downloads/wrapper/hqc_rsdecod_err_val.v
  C:/Users/THUAN/Downloads/wrapper/hqc_rsdecod_roots.v
  C:/Users/THUAN/Downloads/wrapper/hqc_rsdecod_syndromes.v
  C:/Users/THUAN/Downloads/wrapper/hqc_rsdecod_top.v
  C:/Users/THUAN/Downloads/wrapper/hqc_rsdecod_zpoly.v
  C:/Users/THUAN/Downloads/wrapper/karatsuba_small.v
  C:/Users/THUAN/Downloads/wrapper/keccak_top.v
  C:/Users/THUAN/Downloads/wrapper/keygen.v
  C:/Users/THUAN/Downloads/wrapper/loc_based_adder.v
  C:/Users/THUAN/Downloads/wrapper/mem_dual.v
  C:/Users/THUAN/Downloads/wrapper/mem_single.v
  C:/Users/THUAN/Downloads/wrapper/mod34.v
  C:/Users/THUAN/Downloads/wrapper/onegen.v
  C:/Users/THUAN/Downloads/wrapper/onegen_ct.v
  C:/Users/THUAN/Downloads/wrapper/poly_mult.v
  C:/Users/THUAN/Downloads/wrapper/rc.v
  C:/Users/THUAN/Downloads/wrapper/reed_muller_encode.v
  C:/Users/THUAN/Downloads/wrapper/reed_solomon_encode.v
  C:/Users/THUAN/Downloads/wrapper/rm_encoder.v
  C:/Users/THUAN/Downloads/wrapper/state_ram.v
  C:/Users/THUAN/Downloads/wrapper/stateram_inference.v
  C:/Users/THUAN/Downloads/wrapper/syncfifo.v
  C:/Users/THUAN/Downloads/wrapper/transform.v
  C:/Users/THUAN/Downloads/wrapper/v_minus_uy.v
  C:/Users/THUAN/Downloads/wrapper/vect_set_random.v
  C:/Users/THUAN/Downloads/wrapper/xor_based_adder.v
  C:/Users/THUAN/Downloads/wrapper/HQC_wrapper.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top HQC_wrapper -part xck26-sfvc784-2LV-c
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef HQC_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file HQC_wrapper_utilization_synth.rpt -pb HQC_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
